function create_control(obj,event)
	cfig = figure;
	set(cfig,'numbertitle','off');               % erase figure number
	set(cfig,'name','Control panel');
	set(cfig,'MenuBar','none');                  % erase menu
	set(cfig,'doublebuffer','on');               % two graphic buffers
	set(cfig,'CloseRequestFcn',@close_control)          % close request function (close window)
	set(cfig,'tag','control');              % identify figure
    set(cfig,'Units','Normalized','Position',[0.1,0.1,0.4,0.5]);
    
    %--------------------------squares GUI-------------------------------
    draw_square(0.05,0.015,0.45,0.85,0.01);
    draw_square(0.5,0.015,0.45,0.85,0.01);
    draw_square(0.5,0.015,0.45,0.25,0.01);
    draw_square(0.5,0.255,0.45,0.19,0.01);
    %----------------------------sliders---------------------------------
    global w1
    global w2
    global vel1
    global vel2 
    global lookahead
    global freq
    
    uicontrol('Style', 'slider','Tag','sensitivity1',...
        'Min',0,'Max',1,'Value',vel1,...
        'Units','Normalized','Position', [0.075 0.7 0.4 0.05],...
        'Callback', @adjust_vel1); 
    uicontrol('Style', 'slider','Tag','sensitivity1',...
        'Min',0,'Max',1,'Value',w1,...
        'Units','Normalized','Position', [0.075 0.5 0.4 0.05],...
        'Callback', @adjust_w1); 
    uicontrol('Style', 'slider','Tag','sensitivity2',...
        'Min',0,'Max',1,'Value',vel2,...
        'Units','Normalized','Position', [0.075 0.3 0.4 0.05],...
        'Callback', @adjust_vel2); 
    uicontrol('Style', 'slider','Tag','sensitivity1',...
        'Min',0,'Max',1,'Value',w2,...
        'Units','Normalized','Position', [0.075 0.1 0.4 0.05],...
        'Callback', @adjust_w2); 

    %---------------------texts for box 1----------------------------------
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.05 0.9 0.9 0.07],'ForegroundColor',[1 1 1],'BackgroundColor',[0.7 0.7 0.7],...
        'String','Control Panel','FontSize',20);
    %labels for the robot 1 sliders
    global vel1_text
    global vel2_text
    global w1_text
    global w2_text
    global l_text
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.09 0.44 0.05 0.05],...
        'String','0','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.39 0.44 0.1 0.05],...
        'String','1','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.075 0.57 0.4 0.05],...
        'String','Angular velocity robot 1','FontSize',15); 
    w1_text = uicontrol('Style','text','Units','Normalized',...
        'Position',[0.175 0.44 0.2 0.05],...
        'String',w1,'FontSize',12);
    
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.09 0.64 0.05 0.05],...
        'String','0','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.39 0.64 0.1 0.05],...
        'String','1','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.075 0.77 0.4 0.05],...
        'String','Linear velocity robot 1','FontSize',15); 
    vel1_text = uicontrol('Style','text','Units','Normalized',...
        'Position',[0.175 0.64 0.2 0.05],...
        'String',vel1,'FontSize',12);
    
    %labels for the robot 2 sliders
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.09 0.24 0.05 0.05],...
        'String','0','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.39 0.24 0.1 0.05],...
        'String','1','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.075 0.37 0.4 0.05],...
        'String','Linear velocity robot 2','FontSize',15);
    vel2_text = uicontrol('Style','text','Units','Normalized',...
        'Position',[0.175 0.24 0.2 0.05],...
        'String',vel2,'FontSize',12);
    
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.09 0.04 0.05 0.05],...
        'String','0','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.39 0.04 0.1 0.05],...
        'String','1','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.075 0.17 0.4 0.05],...
        'String','Angular velocity robot 2','FontSize',15);
    w2_text = uicontrol('Style','text','Units','Normalized',...
        'Position',[0.175 0.04 0.2 0.05],...
        'String',w2,'FontSize',12);
    %------------------------texts for box 2------------------------------
    uicontrol('Style','text','Units','Normalized',...
    'Position',[0.55 0.775 0.35 0.05],...
    'String','enable camera for robot 1','FontSize',15);
    uicontrol('Style','text','Units','Normalized',...
    'Position',[0.55 0.65 0.35 0.05],...
    'String','enable camera for robot 2','FontSize',15);
    uicontrol('Style','text','Units','Normalized',...
    'Position',[0.54 0.525 0.36 0.05],...
    'String','enable reactive methods','FontSize',15);
    uicontrol('Style','text','Units','Normalized',...
    'Position',[0.58 0.375 0.35 0.05],...
    'String','Mapping frequency','FontSize',15);
    %---------------------------checkboxes---------------------------------
     uicontrol('Style','checkbox','Units','Normalized','Value',1,...
    'Position',[0.575 0.725 0.35 0.05],'Callback',@enable,...
    'String','enable camera 1','FontSize',12,'Tag','enable1');
    uicontrol('Style','checkbox','Units','Normalized','Value',1,...
    'Position',[0.575 0.6 0.35 0.05],'Callback',@enable,...
    'String','enable camera 2','FontSize',12,'Tag','enable2');   
    uicontrol('Style','checkbox','Units','Normalized','Value',0,...
    'Position',[0.575 0.475 0.35 0.05],'Callback',@enable,...
    'String','enable reactive with mapping','FontSize',12,'Tag','enable_nav'); 
    %------------------------edit for freq-------------------------------
    uicontrol('Style','edit','Units','Normalized','Value',freq,'String',num2str(freq),...
        'Position',[0.67 0.31 0.1 0.05],...
        'FontSize',12,'Callback',@adjust_freq);
    %-------------------------slider lookahead----------------------------
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.55 0.04 0.05 0.05],...
        'String','0','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.825 0.04 0.1 0.05],...
        'String','2','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.575 0.17 0.3 0.05],...
        'String','lookahead distance','FontSize',15);
    l_text = uicontrol('Style','text','Units','Normalized',...
        'Position',[0.66 0.04 0.1 0.05],...
        'String',lookahead,'FontSize',12);
    uicontrol('Style', 'slider','Tag','lookahead',...
        'Min',0,'Max',2,'Value',lookahead,...
        'Units','Normalized','Position', [0.55 0.1 0.35 0.05],...
        'Callback', @adjust_l); 

end
function enable(obj,event)
    global enable1
    global enable2
    global img2_handle
    global img1_handle
    global enable_nav
    
    if strcmp(obj.Tag,'enable1') && obj.Value==1
        enable1=true;
    elseif strcmp(obj.Tag,'enable1') && obj.Value==0
        enable1=false;
        set(img1_handle,'visible', 'off');
    elseif strcmp(obj.Tag,'enable2') && obj.Value==1
        enable2=true;
    elseif strcmp(obj.Tag,'enable2') && obj.Value==0
        enable2=false;
        set(img2_handle,'visible', 'off');
    elseif strcmp(obj.Tag,'enable_nav') && obj.Value==1
        enable_nav=true;
    elseif strcmp(obj.Tag,'enable_nav') && obj.Value==0
        enable_nav=false;
    else
        disp('error, something with checkboxes went wrong');
    end
end
function close_control(obj,event)
closereq;
end







