function create_control(obj,event)
	cfig = figure;
	set(cfig,'numbertitle','off');               % erase figure number
	set(cfig,'name','Control panel');
	set(cfig,'MenuBar','none');                  % erase menu
	set(cfig,'doublebuffer','on');               % two graphic buffers
	set(cfig,'CloseRequestFcn',@close_control)          % close request function (close window)
	set(cfig,'tag','control');              % identify figure
    set(cfig,'Units','Normalized','Position',[0.1,0.1,0.4,0.5]);
    
    %----------------------------sliders---------------------------------
    global w1
    global w2
    global vel1
    global vel2 
    
    uicontrol('Style', 'slider','Tag','sensitivity1',...
        'Min',0,'Max',1,'Value',vel1,...
        'Units','Normalized','Position', [0.1 0.7 0.8 0.05],...
        'Callback', @adjust_vel1); 
    uicontrol('Style', 'slider','Tag','sensitivity1',...
        'Min',0,'Max',1,'Value',w1,...
        'Units','Normalized','Position', [0.1 0.5 0.8 0.05],...
        'Callback', @adjust_w1); 
    uicontrol('Style', 'slider','Tag','sensitivity2',...
        'Min',0,'Max',1,'Value',vel2,...
        'Units','Normalized','Position', [0.1 0.3 0.8 0.05],...
        'Callback', @adjust_vel2); 
    uicontrol('Style', 'slider','Tag','sensitivity1',...
        'Min',0,'Max',1,'Value',w2,...
        'Units','Normalized','Position', [0.1 0.1 0.8 0.05],...
        'Callback', @adjust_w2); 
    
    %-----------------------------texts----------------------------------
    %title
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.05 0.9 0.9 0.07],'ForegroundColor',[1 1 1],'BackgroundColor',[0.7 0.7 0.7],...
        'String','Control Panel','FontSize',20);
    %labels for the robot 1 sliders
    global vel1_text
    global vel2_text
    global w1_text
    global w2_text
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.05 0.44 0.2 0.05],...
        'String','0','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.75 0.44 0.2 0.05],...
        'String','1','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.3 0.57 0.4 0.05],...
        'String','Angular velocity robot 1','FontSize',15); 
    w1_text = uicontrol('Style','text','Units','Normalized',...
        'Position',[0.4 0.44 0.2 0.05],...
        'String',w1,'FontSize',12);
    
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.05 0.64 0.2 0.05],...
        'String','0','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.75 0.64 0.2 0.05],...
        'String','1','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.3 0.77 0.4 0.05],...
        'String','Linear velocity robot 1','FontSize',15); 
    vel1_text = uicontrol('Style','text','Units','Normalized',...
        'Position',[0.4 0.64 0.2 0.05],...
        'String',vel1,'FontSize',12);
    
    %labels for the robot 2 sliders
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.05 0.24 0.2 0.05],...
        'String','0','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.75 0.24 0.2 0.05],...
        'String','1','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.3 0.37 0.4 0.05],...
        'String','Linear velocity robot 2','FontSize',15);
    vel2_text = uicontrol('Style','text','Units','Normalized',...
        'Position',[0.4 0.24 0.2 0.05],...
        'String',vel2,'FontSize',12);
    
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.05 0.04 0.2 0.05],...
        'String','0','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.75 0.04 0.2 0.05],...
        'String','1','FontSize',12);
    uicontrol('Style','text','Units','Normalized',...
        'Position',[0.3 0.17 0.4 0.05],...
        'String','Angular velocity robot 2','FontSize',15);
    w2_text = uicontrol('Style','text','Units','Normalized',...
        'Position',[0.4 0.04 0.2 0.05],...
        'String',w2,'FontSize',12);
end
function close_control(obj,event)
closereq;
end

