function draw_square(x,y,h,v,w)
%square drawing funcrion where
%   (x,y): left down x coordenates for the square
%   h: horizontal segment
%   v: vertical segment
%   w: width

    uicontrol('Style', 'text',...
    'Units','Normalized','Position', [x y w v],...
    'BackgroundColor',[0.7 0.7 0.7]); 
    uicontrol('Style', 'text',...
    'Units','Normalized','Position', [x+h-w y w v],...
    'BackgroundColor',[0.7 0.7 0.7]); 
    uicontrol('Style', 'text',...
    'Units','Normalized','Position', [x y h w*2],...
    'BackgroundColor',[0.7 0.7 0.7]); 
    uicontrol('Style', 'text',...
    'Units','Normalized','Position', [x y+v-w h w*2],...
    'BackgroundColor',[0.7 0.7 0.7]); 
end

